name: silage_tracker
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.5+5

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.1
  flutter_localizations:
    sdk: flutter
  path: ^1.8.3
  supabase_flutter: ^2.3.1
  app_links: ^3.5.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
