name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'

      - name: Set up keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Get dependencies
        run: flutter pub get

      - name: Configure Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew wrapper

      - name: Build APK
        run: |
          flutter build apk --release
          cd build/app/outputs/flutter-apk/
          mv app-release.apk silage-tracker-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: silage-tracker-release
          path: build/app/outputs/flutter-apk/silage-tracker-release.apk
